language: php

php:
  - 7.2
  - 7.1
  - 7.0

matrix:
  allow_failures:
    - php: 7.2

before_script:
  - git --version
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit --coverage-clover coverage.xml

after_script:
  # upload coverage
  - wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
  - php coveralls.phar --verbose
