language: php

php:
  - 7.2
  - 7.1
  - 7.0
  
before_script:
  - git --version
  - composer install --prefer-dist
  
script:
  - vendor/bin/phpunit

after_script:
  - vendor/bin/ocular code-coverage:upload --format=php-clover build/logs/clover.xml

