language: php

matrix:
  include:
    - php: 7.1
      env: CODING_STANDARD=true
    - php: 7.1
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"
    - php: 7.2

before_script:
  - git --version
  - composer install --prefer-dist

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug
  - phpenv config-rm xdebug.ini || return 0
  - if [[ $CODING_STANDARD != "" ]]; then composer check-cs; fi

after_script:
  # upload coverage
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
      wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar
      php coveralls.phar --verbose
    fi

notifications:
  email: never
