language: php

matrix:
  include:
    - php: '7.1'
      env: COMPOSER_FLAGS=--prefer-lowest
    - php: '7.1'
      env: STATIC_ANALYSIS=true
    - php: '7.1'
      env: PHPUNIT_FLAGS="--coverage-clover coverage.xml"
    - php: '7.2'
    - php: '7.3'
    - php: '7.4snapshot'

install:
  - composer update $COMPOSER_FLAGS

before_script:
  - git --version

script:
  - vendor/bin/phpunit $PHPUNIT_FLAGS
  # disable xdebug if not needed
  - if [[ $PHPUNIT_FLAGS != "" ]]; then phpenv config-rm xdebug.ini; fi

  - |
    if [[ $STATIC_ANALYSIS == true ]]; then
        composer check-cs
        composer phpstan
    fi

after_script:
  # upload coverage.xml to Coveralls
  - |
    if [[ $PHPUNIT_FLAGS != "" ]]; then
        wget https://github.com/satooshi/php-coveralls/releases/download/v1.0.1/coveralls.phar;
        php coveralls.phar --verbose;
    fi

notifications:
  email: false
