language: php

php:
    - '7.2'
    - '7.3'
    - '7.4snapshot'

before_script:
    - git --version
    # disable xdebug if not coverage
    - phpenv config-rm xdebug.ini || echo "xdebug not available"

script:
    - vendor/bin/phpunit

matrix:
    fast_finish: true

install:
    - composer install

jobs:
    include:
        -
            stage: test
            name: 'Lowest Dependencies'
            php: 7.2
            install:
                # install lowest dependencies
                - composer update --prefer-lowest --no-progress

        -
            stage: test
            name: Unit Tests

        -
            stage: test
            name: ECS
            php: 7.3
            script:
                - composer check-cs

        -
            stage: test
            name: PHPStan
            php: 7.3
            script:
                - composer phpstan

        -
            stage: coverage
            name: Test Coverage
            if: branch = master AND type = push
            php: 7.3
            before_install:
                - echo "keep xdebug"
            script:
                # code coverage run + upload to coveralls.io
                - vendor/bin/phpunit --coverage-clover coverage.xml
                - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
                - php php-coveralls.phar --verbose

notifications:
    email: false
