name: Code_Checks

on:
    pull_request: null
    push:
        branches:
            - master

jobs:
    ecs:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer check-cs

    phpstan:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer phpstan

    rector:
        runs-on: ubuntu-latest

        steps:
            -   uses: actions/checkout@v2
            -   uses: shivammathur/setup-php@v1
                with:
                    php-version: 7.3
                    coverage: none

            -   run: composer install --no-progress
            -   run: composer rector
